=== JimmyTournemaine/dev-tutorial/dev-tutorial-api/public/tutorial.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": [
        "name",
        "resume",
        "slug",
        "slides"
    ],
    "properties": {
        "name": {
            "type": "string",
            "minimum": 3
        },
        "resume": {
            "type": "string",
            "minimum": 10
        },
        "slug": {
            "type": "string",
            "pattern": "^[a-z-]{3,}$"
        },
        "icon": {
            "type": "string",
            "format": "uri"
        },
        "description": {
            "type": "string",
            "minimum": 30
        },
        "slides": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "src",
                    "validators"
                ],
                "additionalProperties": false,
                "properties": {
                    "src": {
                        "type": "string",
                        "format": "uri-reference"
                    },
                    "validators": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/validatorSet"
                        },
                        "minItems": 1
                    }
                }
            }
        }
    },
    "additionalProperties": false,
    "definitions": {
        "validatorSet": {
            "type": "object",
            "additionalProperties": false,
            "minProperties": 1,
            "properties": {
                "prevalidate": {
                    "$ref": "#/definitions/prevalidation"
                },
                "input": {
                    "$ref": "#/definitions/prevalidation"
                },
                "rc": {
                    "$ref": "#/definitions/exitCode"
                },
                "exitCode": {
                    "$ref": "#/definitions/exitCode"
                },
                "creates": {
                    "$ref": "#/definitions/creates"
                }
            }
        },
        "prevalidation": {
            "type": "object",
            "required": [
                "cmd"
            ],
            "additionalProperties": false,
            "properties": {
                "cmd": {
                    "type": "string"
                }
            }
        },
        "exitCode": {
            "type": "object",
            "required": [
                "exitCode"
            ],
            "additionalProperties": false,
            "properties": {
                "exitCode": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "creates": {
            "type": "object",
            "required": [
                "type",
                "path"
            ],
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "file",
                        "directory",
                        "absent"
                    ]
                },
                "path": {
                    "type": "string",
                    "format": "uri-reference"
                }
            }
        }
    }
}

=== JimmyTournemaine/dev-tutorial/dev-tutorial-api/test/extra-tuto2/dev5/tutorial.json
{
  "name": "Dev' Tutorial Test",
  "resume": "Not interesting",
  "slug": "dev5",
  "icon": "https://www.stickpng.com/assets/images/5847f981cef1014c0b5e48be.png",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sit amet varius elit. Ut blandit congue faucibus. Mauris hendrerit enim eu magna vehicula, vitae vulputate risus vehicula. Donec ac nisl nec diam molestie rutrum in vel ligula. Phasellus tempus eros et ante accumsan cursus. Sed.",
  "slides": []
}

=== JimmyTournemaine/dev-tutorial/dev-tutorial-api/test/extra-tuto2/dev7/tutorial.json
{
  "name": "Dev' Tutorial Test",
  "resume": "Not interesting",
  "slug": "dev7",
  "icon": "https://www.stickpng.com/assets/images/5847f981cef1014c0b5e48be.png",
  "description": "Phasellus elit leo, sodales in arcu ut, pulvinar tempor lorem. Nam et lacus urna. Quisque id purus vestibulum, fringilla ante eget, dictum orci. Vivamus sollicitudin nisl ut blandit interdum. Aenean eget neque et neque hendrerit finibus ac ut erat. Etiam sodales convallis eros, vitae tempor erat blandit non. Etiam id auctor augue.",
  "slides": []
}

=== JimmyTournemaine/dev-tutorial/dev-tutorial-api/test/extra-tuto/dev3/tutorial.json
{
  "name": "Dev' Tutorial Test",
  "resume": "Not interesting (don't try it...)",
  "slug": "dev3",
  "icon": "https://www.stickpng.com/assets/images/5847f981cef1014c0b5e48be.png",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a nisi rhoncus, porta est in, ornare felis. Donec ut elit ac nibh pharetra facilisis. Pellentesque enim mi, vehicula id diam ut, euismod luctus magna. Suspendisse blandit turpis ut mi varius egestas in nec lorem. Nulla facilisis, metus quis interdum cursus, diam justo pharetra sem, non semper nulla massa eget arcu. Suspendisse quis risus aliquet, accumsan lorem a, fermentum tellus. Vivamus viverra ex ut molestie pellentesque. Praesent imperdiet finibus enim vel interdum.",
  "slides": []
}
